package walletcli

type AutoGenerated struct {
	ID              int             `json:"id"`
	Addr            string          `json:"addr"`
	Addrbind        string          `json:"addrbind"`
	Addrlocal       string          `json:"addrlocal"`
	Network         string          `json:"network"`
	Services        string          `json:"services"`
	Servicesnames   []string        `json:"servicesnames"`
	Relaytxes       bool            `json:"relaytxes"`
	Lastsend        int             `json:"lastsend"`
	Lastrecv        int             `json:"lastrecv"`
	Bytessent       int             `json:"bytessent"`
	Bytesrecv       int             `json:"bytesrecv"`
	Conntime        int             `json:"conntime"`
	Timeoffset      int             `json:"timeoffset"`
	Pingtime        float64         `json:"pingtime"`
	Minping         float64         `json:"minping"`
	Version         int             `json:"version"`
	Subver          string          `json:"subver"`
	Inbound         bool            `json:"inbound"`
	Addnode         bool            `json:"addnode"`
	Masternode      bool            `json:"masternode"`
	Startingheight  int             `json:"startingheight"`
	Banscore        int             `json:"banscore"`
	SyncedHeaders   int             `json:"synced_headers"`
	SyncedBlocks    int             `json:"synced_blocks"`
	Inflight        []any           `json:"inflight"`
	Whitelisted     bool            `json:"whitelisted"`
	Permissions     []any           `json:"permissions"`
	BytessentPerMsg BytessentPerMsg `json:"bytessent_per_msg"`
	BytesrecvPerMsg BytesrecvPerMsg `json:"bytesrecv_per_msg"`
}
type BytessentPerMsg struct {
	Getaddr      int `json:"getaddr"`
	Getsporks    int `json:"getsporks"`
	Ping         int `json:"ping"`
	Pong         int `json:"pong"`
	Sendaddrv2   int `json:"sendaddrv2"`
	Sendcmpct    int `json:"sendcmpct"`
	Senddsq      int `json:"senddsq"`
	Sendheaders2 int `json:"sendheaders2"`
	Verack       int `json:"verack"`
	Version      int `json:"version"`
}
type BytesrecvPerMsg struct {
	Addrv2       int `json:"addrv2"`
	Ping         int `json:"ping"`
	Pong         int `json:"pong"`
	Sendaddrv2   int `json:"sendaddrv2"`
	Sendcmpct    int `json:"sendcmpct"`
	Senddsq      int `json:"senddsq"`
	Sendheaders2 int `json:"sendheaders2"`
	Verack       int `json:"verack"`
	Version      int `json:"version"`
}
